name: Angular Build, Upload to S3, and Deploy to AWS CodeDeploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build the Angular project
      run: npm run build --prod

    - name: Create the archive
      run: tar -czf build.tar.gz dist/

    - name: Upload artifact to S3
      run: aws s3 cp build.tar.gz s3://awss3forproject1/build.tar.gz --region ap-south-1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Deploy to AWS CodeDeploy
      run: |
        aws deploy create-deployment \
          --application-name CICD \
          --deployment-group-name dev-CICD \
          --s3-location bucket=awss3forproject1,key=build.tar.gz,bundleType=tgz \
          --region ap-south-1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
