name: Angular Build, Upload to S3, and Deploy to AWS CodeDeploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build the Angular project
      run: npm run build -- --configuration=production

    - name: Prepare deployment package
      run: |
        mkdir -p deploy
        cp -r dist/ deploy/
        cp appspec.yml deploy/
        cp -r scripts/ deploy/
        cd deploy && zip -r ../deploy.zip . && cd ..

    - name: Upload artifact to S3
      run: aws s3 cp deploy.zip s3://awss3forproject1/ --region ap-south-1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to AWS CodeDeploy
      run: |
        aws deploy create-deployment \
          --application-name CICD \
          --deployment-group-name dev-CICD \
          --s3-location bucket=awss3forproject1,key=deploy.zip,bundleType=zip \
          --region ap-south-1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
